# Generated by Django 4.1.7 on 2023-03-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinsamount',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
