# Generated by Django 4.1.7 on 2023-03-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_credit_delete_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='credit',
            new_name='balance',
        ),
    ]
